apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
  app: nginx
spec:
 replicas: 4
 selector:
  matchLabels:
   app: nginx
 minReadySeconds: 5 #Wait for 5 seconds before create another pod
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 0 #Total Pods = Replicas+MaxSurge
   maxUnavailable: 1 # Terminates 1 container and creates another one if any changes are made to Yaml
 template:
  metadata:
   labels: 
    app: nginx
  spec:
   containers:
   - name: nginx
     image: nginx:1.14.2
     ports:
     - containerPort: 80