apiVersion: v1
kind: Pod
metadata:
 name: pv-nginx
spec:
 volumes:
 - name: pv-storage
   persistentVolumeClaim:
    claimName: persistent-volume-claim
 containers:
 - name: pv-container
   image: nginx
   ports:
   - containerPort: 80
     name: "nginx-server"
   volumeMounts:
   - mountPath: "/usr/share/nginx"
     name: pv-storage
